
eksctl utils associate-iam-oidc-provider \
  --region ap-south-1 \
  --cluster eks-devops-demo \
  --approve

 
 
curl -o iam_policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json
 
aws iam create-policy   --policy-name AWSLoadBalancerControllerIAMPolicyProdOtherApis  --policy-document file://iam_policy.json
 
 
eksctl create iamserviceaccount \
 --cluster eks-devops-demo \
 --namespace kube-system \
 --name aws-load-balancer-controller \
 --attach-policy-arn arn:aws:iam::666930281169:policy/AWSLoadBalancerControllerIAMPolicy \
 --approve


curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash 
 
helm repo add eks https://aws.github.io/eks-charts
helm repo update
 
 
helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
 -n kube-system \
 --set clusterName=eks-devops-demo \
 --set serviceAccount.create=false \
 --set serviceAccount.name=aws-load-balancer-controller \
 --set region=ap-south-1 \
 --set vpcId=vpc-0241b8af9606393bb \
 --set image.tag="v2.7.1"
 
kubectl get deployment -n kube-system aws-load-balancer-controller